In [1]:
import os
import pandas as pd
from pathlib import Path
from patent_retrieval import utils as utils, dataset as dataset

In [2]:
from patent_retrieval.dataset import parse_patent as parse_patent
from tqdm import tqdm

In [3]:
test_topics_path=(Path(os.environ["CLEF_IP_LOCATION"])/ "02_topics"/ "test-pac"/ "relass_clef-ip-2011-PAC_abs.txt")
candidates_path=Path("/home/alm3rng/patent-retrieval/embeddings/runs/patQwen3-emb-4b-v2_db-v4_all-topics_abstract-claims_aysm_top1000/results.csv")

In [4]:
candidates_df = pd.read_csv(candidates_path)
candidates_df.head()

           topic         number     score
0  EP-1221372-A2  WO-2002004219  0.820527
1  EP-1221372-A2     EP-1029674  0.798651
2  EP-1221372-A2     EP-0703079  0.793282
3  EP-1221372-A2     EP-1514688  0.789982
4  EP-1221372-A2     EP-1193065  0.787915

## Sample 9 topics

In [4]:
topics_9 = [" EP-1223076-A1"," EP-1328127-A1"," EP-1467369-A1"," EP-1474992-A1"," EP-1547481-A1"," EP-1474992-A1"," EP-1662788-A1"," EP-1552963-A1"," EP-1690995-A1"]

## Sample 30 topics

In [5]:
unique_topics = candidates_df['topic'].unique()
n = min(30, len(unique_topics))
topics_30 = pd.Series(unique_topics).sample(n, random_state=42).tolist()
sample_30topics_df = candidates_df[candidates_df['topic'].isin(topics_30)].reset_index(drop=True)
sample_30topics_df

               topic      number     score
0      EP-1243277-A1  EP-1192953  0.950939
1      EP-1243277-A1  EP-1201254  0.849311
2      EP-1243277-A1  EP-0880163  0.774603
3      EP-1243277-A1  EP-0840349  0.763149
4      EP-1243277-A1  EP-0432573  0.762457
...              ...         ...       ...
29995  EP-1936750-A1  EP-0686798  0.651722
29996  EP-1936750-A1  EP-0690325  0.651721
29997  EP-1936750-A1  EP-0824280  0.651696
29998  EP-1936750-A1  EP-0106518  0.651548
29999  EP-1936750-A1  EP-0335756  0.651538

[30000 rows x 3 columns]

In [7]:
topics_30

['EP-1452422-A1',
 'EP-1394086-A1',
 'EP-1580034-A1',
 'EP-1249251-A1',
 'EP-1403982-A1',
 'EP-1260334-A1',
 'EP-1600824-A1',
 'EP-1452567-A1',
 'EP-1936750-A1',
 'EP-1510785-A1',
 'EP-1520990-A2',
 'EP-1484206-A1',
 'EP-1536380-A1',
 'EP-1802174-A1',
 'EP-1589224-A1',
 'EP-1759605-A2',
 'EP-1243277-A1',
 'EP-1742475-A1',
 'EP-1444944-A2',
 'EP-1612985-A1',
 'EP-1282090-A1',
 'EP-1637693-A1',
 'EP-1413530-A1',
 'EP-1262927-A1',
 'EP-1364707-A1',
 'EP-1431110-A1',
 'EP-1394311-A1',
 'EP-1424667-A2',
 'EP-1621102-A2',
 'EP-1803777-A2']

In [6]:
sample_30topics_df.to_csv("/home/alm3rng/patent-retrieval/embeddings/runs/patQwen3-emb-4b-v2_db-v4_all-topics_abstract-claims_aysm_top1000/30topics_results.csv", index=False)

## Sample 500 topics

In [6]:
test_df = utils.load_topics(test_topics_path)

In [7]:
labels_df = pd.read_csv(
    test_topics_path,
    sep="\t",
    header=None,
    names=["topic", "candidate", "label"]
)

In [41]:
import random

# Read the 30 topics from file
with open("/home/alm3rng/patent-retrieval/src/patent_retrieval/dataset/topics/30topics.txt", "r") as f:
    topics_from_file = [line.strip() for line in f if line.strip()]
    # Parse topics from test_df instead of reading test_topics_path
    
    topics_rel_counts = labels_df.groupby("topic").size().to_dict()


    # Filter topics with <= 15 relevant docs
    eligible_topics = {t for t, count in topics_rel_counts.items() if count <= 20}

    # Exclude topics already in the 30 topics file
    topics_from_file_set = set(topics_from_file)
    remaining_eligible = [t for t in eligible_topics if t not in topics_from_file_set]

    # Sample 470 from the remaining eligible topics
    sample_n = min(470, len(remaining_eligible))
    #random.shuffle(remaining_eligible)
    additional_topics = pd.Series(remaining_eligible).sample(sample_n, random_state=6543).tolist()#986745

    # Combine to get 500 topics
    topics_500 = topics_from_file + additional_topics
    print(f"Total topics: {len(topics_500)}")
    print(f"Topics from file: {len(topics_from_file)}")
    print(f"Additional sampled: {len(additional_topics)}")

output_path = Path("/home/alm3rng/patent-retrieval/src/patent_retrieval/dataset/topics/500topics.txt")
with open(output_path, "w") as out_f:
    out_f.write("\n".join(topics_500) + "\n")

print(f"Saved {len(topics_500)} topics to {output_path}")

Total topics: 500
Topics from file: 30
Additional sampled: 470
Saved 500 topics to /home/alm3rng/patent-retrieval/src/patent_retrieval/dataset/topics/500topics.txt

In [42]:
import plotly.express as px
# Plot distribution of relevant documents per topic


relevant_counts = (
    labels_df[
        labels_df["topic"].isin(topics_500) & (labels_df["label"] > 0)
    ]
    .groupby("topic")
    .size()
    .reindex(topics_500, fill_value=0)
)

fig = px.histogram(
    x=relevant_counts.values,
    nbins=30,
    title='Distribution of Relevant Documents per Topic',
    labels={'x': 'Number of Relevant Documents', 'y': 'Number of Topics'},
    opacity=0.7
)
fig.update_layout(
    xaxis_title='Number of Relevant Documents',
    yaxis_title='Frequency',
    showlegend=False
)
fig.show()

print(f"Total topics: {len(relevant_counts)}")
print(f"Avg relevant docs per topic: {relevant_counts.mean():.2f}")
print(f"Min: {relevant_counts.min()}, Max: {relevant_counts.max()}")
print(f"Median: {relevant_counts.median()}")

Total topics: 500
Avg relevant docs per topic: 4.70
Min: 1, Max: 20
Median: 4.0

In [43]:
document_collection_dir=Path(os.environ["CLEF_IP_LOCATION"]) / "01_document_collection" / "document_collection_pac"

def parse_candidate_path(patent_id: str): 

    if patent_id[:2] == 'EP':
        return f"{patent_id[:2]}/{"000000" if patent_id[3] == '0' else "000001"}/{patent_id[4:6]}/{patent_id[6:8]}/{patent_id[8:10]}/{patent_id}*.xml"
    else:
        return f"{patent_id[:2]}/00{patent_id[3:7]}/{patent_id[7:9]}/{patent_id[9:11]}/{patent_id[11:13]}/{patent_id}*.xml"


def find_patent_file(identifier: str) :
    # first try the test topics PAC_topics/files (same approach as get_patent)

    topic_glob = list(test_topics_path.parent.glob(f"PAC_topics/files/{identifier}*.xml"))

    if topic_glob:
        return topic_glob[0]
    # then try the document collection dirs (document_collection_dir is a tuple)

    topic_glob = list(document_collection_dir.glob(parse_candidate_path(identifier)))
    #print(parse_candidate_path(identifier))
    #print(topic_glob)
    #print(topic_glob)
    return topic_glob[0]

In [44]:
topics_500_path = Path("/home/alm3rng/patent-retrieval/src/patent_retrieval/dataset/topics/500topics.txt")
topics_500 = [
    line.strip()
    for line in topics_500_path.read_text(encoding="utf-8").splitlines()
    if line.strip() and not line.strip().startswith("#")
]

#topics_500_df = pd.DataFrame({"topic": topics_500})
topic_languages = {}

for topic in tqdm(topics_500):
    topic_languages[topic] = parse_patent([find_patent_file(topic)])[0].language
topic_languages

100%|██████████| 500/500 [01:09<00:00,  7.21it/s]

{'EP-1452422-A1': 'FR',
 'EP-1394086-A1': 'DE',
 'EP-1580034-A1': 'DE',
 'EP-1249251-A1': 'DE',
 'EP-1403982-A1': 'EN',
 'EP-1260334-A1': 'FR',
 'EP-1600824-A1': 'EN',
 'EP-1452567-A1': 'EN',
 'EP-1936750-A1': 'DE',
 'EP-1510785-A1': 'EN',
 'EP-1520990-A2': 'EN',
 'EP-1484206-A1': 'FR',
 'EP-1536380-A1': 'EN',
 'EP-1802174-A1': 'DE',
 'EP-1589224-A1': 'DE',
 'EP-1759605-A2': 'DE',
 'EP-1243277-A1': 'EN',
 'EP-1742475-A1': 'FR',
 'EP-1444944-A2': 'DE',
 'EP-1612985-A1': 'FR',
 'EP-1282090-A1': 'FR',
 'EP-1637693-A1': 'FR',
 'EP-1413530-A1': 'FR',
 'EP-1262927-A1': 'FR',
 'EP-1364707-A1': 'FR',
 'EP-1431110-A1': 'FR',
 'EP-1394311-A1': 'DE',
 'EP-1424667-A2': 'EN',
 'EP-1621102-A2': 'FR',
 'EP-1803777-A2': 'DE',
 'EP-1595940-A1': 'EN',
 'EP-1746183-A1': 'DE',
 'EP-1508384-A2': 'EN',
 'EP-1935503-A1': 'FR',
 'EP-1574231-A1': 'EN',
 'EP-1284321-A1': 'FR',
 'EP-1619441-A1': 'FR',
 'EP-1580185-A1': 'FR',
 'EP-1840940-A1': 'DE',
 'EP-1293751-A1': 'FR',
 'EP-1324317-A1': 'EN',
 'EP-1377050-A1': 'EN',
 'EP-1712319-A1': 'DE',
 'EP-1457297-A2': 'DE',
 'EP-1617171-A1': 'FR',
 'EP-1612844-A1': 'EN',
 'EP-1489144-A1': 'EN',
 'EP-1261053-A1': 'FR',
 'EP-1905694-A1': 'EN',
 'EP-1693606-A1': 'FR',
 'EP-1426459-A1': 'FR',
 'EP-1912140-A1': 'EN',
 'EP-1338289-A1': 'FR',
 'EP-1308409-A1': 'DE',
 'EP-1646262-A1': 'FR',
 'EP-1470884-A1': 'EN',
 'EP-1257012-A2': 'EN',
 'EP-1422809-A2': 'DE',
 'EP-1604648-A1': 'FR',
 'EP-1310414-A1': 'EN',
 'EP-1256397-A1': 'EN',
 'EP-1882482-A2': 'EN',
 'EP-1524429-A1': 'EN',
 'EP-1666481-A2': 'EN',
 'EP-1876533-A1': 'DE',
 'EP-1571692-A2': 'EN',
 'EP-1352624-A2': 'EN',
 'EP-1445380-A2': 'FR',
 'EP-1336487-A2': 'EN',
 'EP-1842425-A1': 'FR',
 'EP-1382322-A2': 'FR',
 'EP-1323366-A2': 'FR',
 'EP-1351413-A1': 'DE',
 'EP-1688335-A1': 'FR',
 'EP-1355441-A1': 'FR',
 'EP-1293193-A1': 'FR',
 'EP-1825734-A1': 'DE',
 'EP-1520594-A1': 'EN',
 'EP-1286165-A2': 'EN',
 'EP-1246473-A1': 'FR',
 'EP-1411143-A1': 'FR',
 'EP-1767660-A1': 'DE',
 'EP-1396712-A2': 'FR',
 'EP-1798472-A2': 'DE',
 'EP-1498217-A2': 'DE',
 'EP-1669763-A1': 'DE',
 'EP-1320135-A2': 'EN',
 'EP-1503326-A1': 'EN',
 'EP-1391717-A1': 'EN',
 'EP-1300507-A2': 'EN',
 'EP-1747778-A1': 'EN',
 'EP-1777781-A1': 'EN',
 'EP-1772933-A1': 'DE',
 'EP-1467425-A1': 'EN',
 'EP-1610087-A1': 'FR',
 'EP-1611795-A1': 'DE',
 'EP-1775809-A1': 'DE',
 'EP-1790627-A1': 'EN',
 'EP-1378205-A1': 'FR',
 'EP-1796451-A1': 'DE',
 'EP-1518507-A1': 'EN',
 'EP-1582280-A1': 'FR',
 'EP-1471341-A1': 'DE',
 'EP-1731009-A1': 'DE',
 'EP-1424115-A1': 'DE',
 'EP-1561878-A1': 'DE',
 'EP-1245384-A2': 'EN',
 'EP-1285988-A1': 'FR',
 'EP-1495729-A1': 'EN',
 'EP-1535564-A2': 'DE',
 'EP-1428690-A1': 'FR',
 'EP-1520798-A1': 'FR',
 'EP-1245985-A2': 'DE',
 'EP-1808285-A1': 'FR',
 'EP-1389026-A1': 'FR',
 'EP-1313309-A1': 'FR',
 'EP-1348466-A2': 'EN',
 'EP-1530982-A1': 'DE',
 'EP-1262965-A1': 'EN',
 'EP-1283439-A1': 'EN',
 'EP-1586765-A1': 'DE',
 'EP-1298874-A1': 'EN',
 'EP-1835477-A1': 'FR',
 'EP-1315319-A1': 'FR',
 'EP-1239648-A1': 'FR',
 'EP-1415623-A1': 'DE',
 'EP-1281734-A1': 'DE',
 'EP-1225290-A2': 'DE',
 'EP-1302128-A1': 'FR',
 'EP-1930214-A2': 'FR',
 'EP-1336882-A2': 'EN',
 'EP-1262483-A1': 'DE',
 'EP-1442885-A1': 'EN',
 'EP-1714578-A1': 'FR',
 'EP-1445596-A1': 'EN',
 'EP-1561761-A1': 'EN',
 'EP-1849979-A2': 'DE',
 'EP-1296503-A2': 'FR',
 'EP-1243350-A1': 'FR',
 'EP-1402876-A2': 'FR',
 'EP-1930093-A1': 'FR',
 'EP-1536052-A2': 'EN',
 'EP-1321292-A2': 'EN',
 'EP-1317903-A1': 'FR',
 'EP-1714870-A1': 'FR',
 'EP-1247868-A2': 'DE',
 'EP-1361702-A1': 'EN',
 'EP-1600775-A2': 'DE',
 'EP-1473556-A1': 'FR',
 'EP-1422200-A2': 'DE',
 'EP-1258929-A2': 'EN',
 'EP-1246066-A2': 'DE',
 'EP-1513063-A1': 'EN',
 'EP-1568519-A1': 'FR',
 'EP-1577219-A1': 'FR',
 'EP-1371935-A1': 'FR',
 'EP-1300975-A1': 'FR',
 'EP-1723988-A1': 'FR',
 'EP-1724001-A2': 'EN',
 'EP-1336417-A1': 'FR',
 'EP-1320011-A2': 'EN',
 'EP-1792573-A1': 'DE',
 'EP-1229084-A1': 'EN',
 'EP-1726359-A1': 'EN',
 'EP-1646123-A1': 'EN',
 'EP-1750102-A2': 'DE',
 'EP-1623650-A2': 'FR',
 'EP-1473763-A1': 'EN',
 'EP-1524701-A2': 'EN',
 'EP-1471459-A2': 'EN',
 'EP-1588688-A1': 'FR',
 'EP-1552963-A1': 'FR',
 'EP-1836916-A1': 'FR',
 'EP-1279510-A1': 'DE',
 'EP-1434071-A1': 'FR',
 'EP-1227590-A1': 'FR',
 'EP-1657334-A1': 'EN',
 'EP-1243404-A1': 'DE',
 'EP-1293215-A1': 'FR',
 'EP-1449688-A2': 'EN',
 'EP-1347606-A1': 'EN',
 'EP-1683986-A1': 'DE',
 'EP-1652523-A1': 'EN',
 'EP-1350866-A1': 'EN',
 'EP-1413363-A1': 'EN',
 'EP-1714688-A1': 'FR',
 'EP-1564190-A1': 'EN',
 'EP-1283031-A2': 'EN',
 'EP-1367289-A1': 'EN',
 'EP-1253478-A2': 'EN',
 'EP-1331716-A1': 'FR',
 'EP-1696595-A2': 'EN',
 'EP-1591613-A1': 'EN',
 'EP-1623758-A1': 'EN',
 'EP-1408299-A2': 'EN',
 'EP-1275639-A1': 'DE',
 'EP-1709881-A1': 'DE',
 'EP-1262813-A1': 'FR',
 'EP-1624528-A2': 'DE',
 'EP-1374945-A1': 'FR',
 'EP-1603361-A1': 'EN',
 'EP-1239266-A2': 'DE',
 'EP-1502783-A2': 'DE',
 'EP-1352644-A1': 'EN',
 'EP-1420199-A1': 'DE',
 'EP-1264978-A2': 'EN',
 'EP-1363353-A1': 'FR',
 'EP-1745885-A1': 'EN',
 'EP-1921443-A1': 'FR',
 'EP-1491519-A1': 'DE',
 'EP-1426669-A2': 'DE',
 'EP-1704916-A1': 'EN',
 'EP-1332759-A1': 'EN',
 'EP-1690745-A1': 'EN',
 'EP-1416182-A2': 'EN',
 'EP-1281393-A2': 'DE',
 'EP-1375885-A1': 'FR',
 'EP-1586348-A1': 'DE',
 'EP-1278070-A2': 'EN',
 'EP-1444973-A1': 'FR',
 'EP-1705357-A1': 'EN',
 'EP-1477899-A2': 'EN',
 'EP-1577273-A2': 'DE',
 'EP-1308492-A2': 'DE',
 'EP-1245876-A2': 'EN',
 'EP-1576883-A1': 'EN',
 'EP-1354713-A2': 'EN',
 'EP-1775354-A1': 'DE',
 'EP-1688302-A1': 'DE',
 'EP-1285572-A1': 'DE',
 'EP-1361535-A1': 'DE',
 'EP-1359239-A1': 'FR',
 'EP-1277460-A2': 'DE',
 'EP-1287981-A2': 'EN',
 'EP-1480263-A1': 'EN',
 'EP-1880798-A1': 'DE',
 'EP-1383220-A2': 'DE',
 'EP-1308899-A2': 'EN',
 'EP-1736578-A2': 'DE',
 'EP-1666085-A1': 'FR',
 'EP-1420539-A2': 'EN',
 'EP-1530177-A1': 'EN',
 'EP-1264770-A1': 'EN',
 'EP-1675432-A1': 'DE',
 'EP-1616554-A1': 'FR',
 'EP-1676603-A1': 'FR',
 'EP-1875795-A1': 'DE',
 'EP-1852810-A1': 'EN',
 'EP-1317920-A1': 'FR',
 'EP-1358911-A1': 'FR',
 'EP-1394065-A1': 'EN',
 'EP-1380425-A1': 'EN',
 'EP-1455312-A1': 'DE',
 'EP-1426016-A1': 'DE',
 'EP-1281358-A1': 'DE',
 'EP-1262456-A1': 'FR',
 'EP-1484935-A1': 'EN',
 'EP-1310767-A1': 'DE',
 'EP-1319726-A1': 'FR',
 'EP-1607297-A1': 'FR',
 'EP-1316456-A2': 'DE',
 'EP-1223325-A1': 'FR',
 'EP-1342905-A1': 'FR',
 'EP-1440874-A1': 'FR',
 'EP-1460307-A2': 'DE',
 'EP-1729360-A1': 'FR',
 'EP-1471753-A1': 'FR',
 'EP-1260379-A2': 'EN',
 'EP-1276286-A2': 'EN',
 'EP-1527714-A1': 'EN',
 'EP-1324251-A2': 'EN',
 'EP-1829837-A1': 'DE',
 'EP-1363484-A2': 'EN',
 'EP-1885045-A1': 'FR',
 'EP-1616602-A1': 'FR',
 'EP-1662234-A1': 'DE',
 'EP-1401065-A1': 'DE',
 'EP-1255101-A2': 'EN',
 'EP-1772258-A1': 'DE',
 'EP-1239515-A1': 'FR',
 'EP-1774872-A1': 'DE',
 'EP-1378905-A1': 'EN',
 'EP-1441131-A1': 'DE',
 'EP-1618947-A1': 'DE',
 'EP-1267141-A2': 'DE',
 'EP-1247963-A2': 'DE',
 'EP-1258265-A1': 'FR',
 'EP-1749670-A1': 'FR',
 'EP-1834913-A1': 'DE',
 'EP-1293936-A1': 'FR',
 'EP-1845611-A1': 'DE',
 'EP-1780003-A1': 'DE',
 'EP-1514487-A1': 'EN',
 'EP-1652825-A2': 'EN',
 'EP-1306130-A1': 'EN',
 'EP-1455014-A1': 'FR',
 'EP-1550432-A2': 'FR',
 'EP-1352689-A1': 'FR',
 'EP-1260509-A1': 'FR',
 'EP-1630530-A1': 'EN',
 'EP-1452102-A2': 'EN',
 'EP-1428506-A1': 'FR',
 'EP-1302562-A1': 'EN',
 'EP-1507231-A1': 'FR',
 'EP-1376112-A1': 'DE',
 'EP-1358801-A1': 'FR',
 'EP-1775095-A1': 'DE',
 'EP-1231669-A1': 'EN',
 'EP-1304027-A1': 'EN',
 'EP-1547951-A1': 'EN',
 'EP-1815931-A1': 'DE',
 'EP-1522673-A1': 'FR',
 'EP-1244206-A1': 'FR',
 'EP-1918933-A2': 'EN',
 'EP-1551005-A1': 'EN',
 'EP-1868267-A2': 'EN',
 'EP-1931179-A1': 'FR',
 'EP-1757328-A1': 'FR',
 'EP-1348951-A1': 'EN',
 'EP-1619404-A1': 'FR',
 'EP-1298637-A2': 'EN',
 'EP-1403611-A1': 'FR',
 'EP-1500472-A1': 'FR',
 'EP-1314620-A1': 'DE',
 'EP-1506957-A1': 'DE',
 'EP-1287816-A1': 'EN',
 'EP-1369432-A2': 'FR',
 'EP-1598787-A2': 'EN',
 'EP-1348906-A1': 'DE',
 'EP-1382738-A1': 'EN',
 'EP-1571135-A2': 'FR',
 'EP-1310682-A2': 'DE',
 'EP-1757196-A2': 'FR',
 'EP-1747879-A2': 'EN',
 'EP-1649967-A1': 'DE',
 'EP-1847547-A1': 'FR',
 'EP-1464324-A1': 'FR',
 'EP-1342873-A2': 'DE',
 'EP-1628067-A1': 'FR',
 'EP-1443135-A1': 'EN',
 'EP-1253340-A2': 'DE',
 'EP-1655390-A1': 'EN',
 'EP-1234898-A1': 'EN',
 'EP-1475994-A2': 'DE',
 'EP-1852831-A1': 'DE',
 'EP-1921550-A1': 'FR',
 'EP-1405627-A1': 'FR',
 'EP-1586826-A1': 'FR',
 'EP-1514886-A1': 'EN',
 'EP-1808677-A1': 'EN',
 'EP-1541350-A1': 'DE',
 'EP-1303119-A1': 'FR',
 'EP-1912046-A1': 'DE',
 'EP-1757427-A2': 'DE',
 'EP-1288965-A2': 'EN',
 'EP-1309130-A1': 'FR',
 'EP-1522309-A1': 'EN',
 'EP-1306591-A2': 'FR',
 'EP-1915958-A1': 'DE',
 'EP-1645619-A1': 'DE',
 'EP-1557878-A2': 'FR',
 'EP-1591101-A1': 'FR',
 'EP-1450121-A2': 'DE',
 'EP-1858116-A1': 'FR',
 'EP-1635082-A1': 'DE',
 'EP-1574433-A1': 'FR',
 'EP-1580754-A1': 'EN',
 'EP-1460019-A1': 'FR',
 'EP-1333113-A1': 'DE',
 'EP-1468671-A1': 'FR',
 'EP-1270703-A2': 'DE',
 'EP-1927345-A1': 'FR',
 'EP-1679907-A1': 'EN',
 'EP-1602995-A1': 'FR',
 'EP-1538656-A1': 'FR',
 'EP-1229104-A2': 'DE',
 'EP-1391817-A2': 'DE',
 'EP-1655750-A2': 'FR',
 'EP-1296307-A2': 'DE',
 'EP-1335524-A1': 'FR',
 'EP-1533270-A1': 'FR',
 'EP-1887503-A1': 'DE',
 'EP-1422915-A1': 'EN',
 'EP-1347200-A2': 'DE',
 'EP-1247521-A1': 'FR',
 'EP-1359566-A1': 'DE',
 'EP-1391904-A2': 'DE',
 'EP-1754841-A2': 'DE',
 'EP-1632220-A1': 'FR',
 'EP-1445533-A2': 'FR',
 'EP-1294154-A2': 'EN',
 'EP-1251432-A2': 'DE',
 'EP-1372298-A1': 'EN',
 'EP-1473562-A1': 'EN',
 'EP-1439605-A1': 'EN',
 'EP-1493559-A1': 'EN',
 'EP-1731137-A1': 'FR',
 'EP-1349411-A1': 'EN',
 'EP-1310606-A2': 'DE',
 'EP-1259089-A1': 'FR',
 'EP-1450573-A1': 'FR',
 'EP-1338316-A1': 'FR',
 'EP-1391946-A2': 'EN',
 'EP-1231742-A1': 'FR',
 'EP-1752418-A1': 'DE',
 'EP-1859786-A1': 'EN',
 'EP-1260611-A2': 'EN',
 'EP-1493938-A1': 'EN',
 'EP-1894596-A2': 'EN',
 'EP-1351051-A1': 'FR',
 'EP-1386610-A1': 'FR',
 'EP-1277427-A1': 'FR',
 'EP-1275414-A1': 'FR',
 'EP-1405566-A2': 'FR',
 'EP-1486930-A1': 'DE',
 'EP-1411343-A2': 'FR',
 'EP-1293502-A1': 'FR',
 'EP-1568804-A2': 'DE',
 'EP-1589790-A2': 'DE',
 'EP-1586299-A1': 'FR',
 'EP-1557088-A1': 'EN',
 'EP-1256984-A2': 'FR',
 'EP-1340485-A2': 'FR',
 'EP-1422858-A1': 'DE',
 'EP-1380733-A2': 'DE',
 'EP-1600432-A1': 'EN',
 'EP-1308988-A1': 'FR',
 'EP-1698839-A2': 'DE',
 'EP-1447753-A1': 'EN',
 'EP-1627835-A1': 'DE',
 'EP-1280290-A1': 'FR',
 'EP-1359628-A2': 'DE',
 'EP-1622231-A1': 'FR',
 'EP-1637524-A1': 'EN',
 'EP-1842751-A1': 'DE',
 'EP-1304102-A2': 'DE',
 'EP-1475139-A1': 'DE',
 'EP-1834631-A1': 'DE',
 'EP-1450005-A1': 'FR',
 'EP-1629940-A2': 'DE',
 'EP-1464342-A1': 'DE',
 'EP-1637699-A2': 'EN',
 'EP-1529517-A2': 'DE',
 'EP-1460124-A1': 'FR',
 'EP-1514600-A1': 'FR',
 'EP-1561930-A1': 'DE',
 'EP-1233540-A1': 'EN',
 'EP-1597976-A1': 'EN',
 'EP-1582406-A1': 'DE',
 'EP-1598218-A1': 'EN',
 'EP-1503225-A2': 'EN',
 'EP-1366985-A2': 'DE',
 'EP-1525860-A1': 'FR',
 'EP-1347603-A1': 'EN',
 'EP-1298004-A1': 'FR',
 'EP-1777722-A2': 'DE',
 'EP-1384446-A1': 'EN',
 'EP-1524451-A1': 'EN',
 'EP-1362662-A1': 'FR',
 'EP-1611874-A1': 'EN',
 'EP-1278319-A2': 'DE',
 'EP-1345234-A1': 'EN',
 'EP-1229366-A2': 'EN',
 'EP-1369635-A1': 'DE',
 'EP-1393996-A1': 'FR',
 'EP-1923315-A1': 'FR',
 'EP-1714855-A2': 'DE',
 'EP-1921898-A1': 'EN',
 'EP-1338221-A1': 'FR',
 'EP-1504706-A1': 'FR',
 'EP-1803778-A2': 'EN',
 'EP-1391322-A1': 'DE',
 'EP-1498642-A1': 'EN',
 'EP-1405680-A1': 'DE',
 'EP-1607582-A1': 'FR',
 'EP-1500382-A1': 'EN',
 'EP-1883080-A1': 'EN',
 'EP-1493406-A2': 'EN',
 'EP-1293740-A2': 'DE',
 'EP-1418338-A2': 'EN',
 'EP-1481645-A1': 'EN',
 'EP-1481597-A1': 'FR',
 'EP-1624106-A1': 'DE',
 'EP-1342463-A1': 'DE',
 'EP-1521207-A2': 'EN',
 'EP-1707917-A2': 'EN',
 'EP-1630076-A1': 'FR',
 'EP-1460852-A1': 'FR',
 'EP-1233614-A1': 'FR',
 'EP-1586921-A1': 'EN',
 'EP-1356802-A1': 'EN',
 'EP-1614599-A1': 'DE',
 'EP-1458081-A2': 'EN',
 'EP-1550667-A1': 'EN',
 'EP-1314384-A2': 'FR',
 'EP-1306381-A1': 'DE',
 'EP-1480181-A1': 'FR',
 'EP-1342843-A1': 'EN',
 'EP-1319801-A2': 'DE',
 'EP-1518464-A1': 'EN'}

In [45]:
topic_language_counts = {}
for lang in ['DE', 'EN', 'FR']:
    topic_language_counts[lang] = sum(1 for tl in topic_languages.values() if tl == lang)

percentages = [f"{(count / len(topic_languages)) * 100:.1f}%" for count in topic_language_counts.values()]

fig = px.bar(
    x=list(topic_language_counts.keys()),
    y=list(topic_language_counts.values()),
    text=percentages,
    labels={'x': 'Language', 'y': 'Number of Topics'},
    width=500,
    height=400,
    color_discrete_sequence=['teal']
)
fig.update_traces(textposition='outside', width=0.4)
fig.update_layout(
    xaxis_title='Language',
    yaxis_title='Number of Topics',
    showlegend=False,
    yaxis_range=[0, max(topic_language_counts.values()) * 1.15]
)
fig.show()